services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Tokyo
